I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/4 - dr danger 1.rpy", line 26, in script
    "{b}[the {/b}{b}dr.{/b}{b} danger screens go {/b}{b}on ]{/b}"
KeyError: 'the {/b}{b}dr'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/4 - dr danger 1.rpy", line 26, in script
    "{b}[the {/b}{b}dr.{/b}{b} danger screens go {/b}{b}on ]{/b}"
  File "E:\Development\renpy-8.0.0-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\character.py", line 1253, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "E:\Development\renpy-8.0.0-sdk\renpy\character.py", line 1172, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "E:\Development\renpy-8.0.0-sdk\renpy\character.py", line 1152, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "E:\Development\renpy-8.0.0-sdk\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "E:\Development\renpy-8.0.0-sdk\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: 'the {/b}{b}dr'

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
malViolence 1.0
Tue Mar 21 19:59:26 2023
